version: '3.7'

services:
  postgres:
    image: postgres:12
    volumes:
      - "postgres_data:/var/lib/postgresql/data/"
    env_file:
      - .env
  market_space:
    build: .
    env_file:
      - .env
    command: ['sh', '.././start.sh']
    ports:
      - "8000:8000"
    depends_on:
      - postgres
  rabbit:
    hostname: rabbit
    image: rabbitmq:3-management
    env_file:
      - .env
    ports:
      - "5672:5672"
      - "15672:15672"
  worker:
    build: .
    env_file:
      - .env
    command: ['celery', '-A', 'marketer_space.celery', 'worker', '-l', 'info']
    links:
      - rabbit
    depends_on:
      - market_space
      - rabbit
  celery-beat:
    build: .
    command: ['celery', '-A', 'marketer_space.celery', 'beat', '-l', 'info']
    volumes:
      - ./project/:/usr/src/app/
    env_file:
      - .env
    depends_on:
      - rabbit
volumes:
  postgres_data: