# Generated by Django 4.0.7 on 2022-10-02 08:46

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_rename_email_contact_mail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='status',
            field=django_fsm.FSMField(choices=[('not_started', 'Not Started'), ('started', 'Started'), ('paused', 'Paused'), ('completed', 'Completed')], default='not_started', max_length=50),
        ),
    ]
